Repository TeamSoundSense/SoundSenseV1, pull requests merged in 2021-04, with the labels that each got.

#67 #66-fix-unnecessary-loudness-warnings
  app/src/main/java/com/example/soundsensev1/MainActivity.java
Labels: bug

#72 #70 edit layout for sign in sign up
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/soundsensev1/LoginActivity.java
  app/src/main/java/com/example/soundsensev1/LoginAdapter.java
  app/src/main/java/com/example/soundsensev1/LoginTabFragment.java
  app/src/main/java/com/example/soundsensev1/RegistrationActivity.java
  app/src/main/java/com/example/soundsensev1/SignUpTabFragment.java
  app/src/main/res/drawable-v24/logo_no_background_with_title.png
  app/src/main/res/drawable-v24/logo_no_title_no_background.png
  app/src/main/res/drawable/button_bg.xml
  app/src/main/res/drawable/edit_text_bg.xml
  app/src/main/res/drawable/vie_bg.xml
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/layout/activity_registration.xml
  app/src/main/res/layout/login_tab_fragment.xml
  app/src/main/res/layout/signup_tab_fragment.xml
Labels: enhancement

#77 #73 updating introductory activity
  app/src/main/java/com/example/soundsensev1/OnBoardingFragment1.java
  app/src/main/java/com/example/soundsensev1/OnBoardingFragment2.java
  app/src/main/java/com/example/soundsensev1/OnBoardingFragment3.java
  app/src/main/res/drawable/arrow_white.png
  app/src/main/res/layout/fragment_on_boarding1.xml
  app/src/main/res/layout/fragment_on_boarding2.xml
  app/src/main/res/layout/fragment_on_boarding3.xml
  app/src/main/res/mipmap-xhdpi/intro_background1.jpg
  app/src/main/res/mipmap-xhdpi/intro_background2.jpg
  app/src/main/res/mipmap-xhdpi/intro_background3.jpg
Labels: enhancement

#78 2 threshold buttons added
  app/src/main/java/com/example/soundsensev1/SettingFragment.java
  app/src/main/res/layout/setting_fragment.xml
Labels: enhancement

#80 #75 adding question mark on fragments
  app/src/main/java/com/example/soundsensev1/DataFragment.java
  app/src/main/java/com/example/soundsensev1/MainFragment.java
  app/src/main/res/drawable-v24/close_icon.png
  app/src/main/res/drawable-v24/data_icon.png
  app/src/main/res/drawable-v24/home_icon.png
  app/src/main/res/drawable-v24/logout_icon.png
  app/src/main/res/drawable-v24/profile_icon.png
  app/src/main/res/drawable-v24/setting_icon.png
  app/src/main/res/drawable-v24/vie_bg2.xml
  app/src/main/res/drawable-v24/white_question_mark.png
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/data_fragment.xml
  app/src/main/res/layout/drawer_menu.xml
  app/src/main/res/layout/main_fragment.xml
  app/src/main/res/values/arrays.xml
  app/src/main/res/values/colors.xml
Labels: enhancement

#82 #81 working on forgot password activity
  app/src/main/java/com/example/soundsensev1/PasswordActivity.java
  app/src/main/java/com/example/soundsensev1/ProfileFragment.java
  app/src/main/res/layout/activity_password.xml
  app/src/main/res/values/colors.xml
Labels: enhancement

#83 #79-change-layout-for-settings-activity
  app/src/main/java/com/example/soundsensev1/SettingFragment.java
  app/src/main/res/drawable-v24/button_bg2.xml
  app/src/main/res/drawable-v24/vie_bg3.xml
  app/src/main/res/layout/setting_fragment.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/themes.xml
Labels: enhancement

#85 #84-range-is-now-int
  app/src/main/java/com/example/soundsensev1/SettingFragment.java
  app/src/main/res/layout/setting_fragment.xml
Labels: bug

#88 #84-change-text-in-introductory-activity
  app/src/main/res/layout/fragment_on_boarding1.xml
  app/src/main/res/layout/fragment_on_boarding2.xml
  app/src/main/res/layout/fragment_on_boarding3.xml
Labels: enhancement

#90 #89-app-icon-and-name-changed
  app/src/main/AndroidManifest.xml
  app/src/main/res/values/strings.xml
Labels: enhancement

#91 #86 changing layout profile activity
  app/src/main/res/drawable-v24/three_dots.png
  app/src/main/res/drawable/edit_text_bg2.xml
  app/src/main/res/layout/data_fragment.xml
  app/src/main/res/layout/profile_fragment.xml
  app/src/main/res/layout/setting_fragment.xml
  app/src/main/res/menu/profile_menu.xml
Labels: enhancement

#92 centered logo added launcher app icon
  app/src/main/AndroidManifest.xml
  app/src/main/res/drawable-v24/centered_logo.png
  app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
Labels: enhancement

#96 #94-history-layout-updated
  app/src/main/java/com/example/soundsensev1/DataFragment.java
  app/src/main/res/layout/data_fragment.xml
Labels: enhancement

#95 #69-finalized-loudness-counts
  app/src/main/java/com/example/soundsensev1/MainActivity.java
  app/src/main/java/com/example/soundsensev1/MainFragment.java
  app/src/main/java/com/example/soundsensev1/SharedPreferencesHelper.java
  app/src/main/res/layout/main_fragment.xml
  github.properties
Labels: enhancement

#101 Layout change on ListView
  app/src/main/res/layout/custom_simple_list_item_1.xml
  build.gradle
Labels: enhancement

#104 #102 fixing the timers
  app/src/main/java/com/example/soundsensev1/MainActivity.java
Labels: bug

#103 #99 change main fragment layout
  app/src/main/java/com/example/soundsensev1/MainFragment.java
  app/src/main/res/drawable/vie_bg4.xml
  app/src/main/res/layout/main_fragment.xml
  app/src/main/res/values/colors.xml
Labels: enhancement

#107 #106-Change-intro-text
  app/src/main/res/layout/fragment_on_boarding1.xml
  app/src/main/res/layout/fragment_on_boarding2.xml
  app/src/main/res/layout/fragment_on_boarding3.xml
Labels: enhancement

#109 enterEditMode() functional!
  app/src/main/java/com/example/soundsensev1/ProfileFragment.java
Labels: bug

#111 #110 attempting to fix on/off bug
  app/src/main/java/com/example/soundsensev1/MainActivity.java
  app/src/main/java/com/example/soundsensev1/MainFragment.java
  app/src/main/res/layout/main_fragment.xml
Labels: bug

#113 #112-button-turns-off-when-logging-out
  app/src/main/java/com/example/soundsensev1/MainActivity.java
  app/src/main/java/com/example/soundsensev1/ProfileFragment.java
Labels: enhancement

#116 #114-stop-return-button
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/soundsensev1/LoginActivity.java
  app/src/main/java/com/example/soundsensev1/MainActivity.java
  app/src/main/java/com/example/soundsensev1/PasswordActivity.java
  app/src/main/java/com/example/soundsensev1/ProfileFragment.java
Labels: bug

#119 #118-idk
  app/src/main/AndroidManifest.xml
Labels: bug

#121 Edit bug fixed
  app/src/main/java/com/example/soundsensev1/ProfileFragment.java
Labels: bug

#123 Edit bug fixed part 2
  app/src/main/java/com/example/soundsensev1/ProfileFragment.java
  app/src/main/res/menu/profile_menu.xml
Labels: enhancement

#125 #124 cleaning up
  app/src/main/java/com/example/soundsensev1/DataFragment.java
  app/src/main/java/com/example/soundsensev1/DrawerAdapter.java
  app/src/main/java/com/example/soundsensev1/IntroductoryActivity.java
  app/src/main/java/com/example/soundsensev1/LoginActivity.java
  app/src/main/java/com/example/soundsensev1/LoginAdapter.java
  app/src/main/java/com/example/soundsensev1/LoginTabFragment.java
  app/src/main/java/com/example/soundsensev1/MainActivity.java
  app/src/main/java/com/example/soundsensev1/MainFragment.java
  app/src/main/java/com/example/soundsensev1/MyService.java
  app/src/main/java/com/example/soundsensev1/OnBoardingFragment1.java
  app/src/main/java/com/example/soundsensev1/OnBoardingFragment2.java
  app/src/main/java/com/example/soundsensev1/OnBoardingFragment3.java
  app/src/main/java/com/example/soundsensev1/ProfileFragment.java
  app/src/main/java/com/example/soundsensev1/SettingFragment.java
  app/src/main/java/com/example/soundsensev1/SharedPreferencesHelper.java
  app/src/main/java/com/example/soundsensev1/SignUpTabFragment.java
  app/src/main/java/com/example/soundsensev1/SimpleItem.java
  app/src/main/java/com/example/soundsensev1/SpaceItem.java
  app/src/main/java/com/example/soundsensev1/User.java
Labels: documentation
