Repository TeamSoundSense/SoundSenseV1, pull requests merged in 2021-03, with the labels that each got.

#2 #1-created-profile-activity-skeleton
  .idea/vcs.xml
  app/src/main/res/layout/activity_profile.xml
Labels: enhancement

#4 #1-fixed-git-ignore
  .gitignore
  .idea/.gitignore
  .idea/vcs.xml
Labels: bug

#6 #5-created-toolbar
  .idea/misc.xml
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/soundsensev1/DataActivity.java
  app/src/main/java/com/example/soundsensev1/MainActivity.java
  app/src/main/java/com/example/soundsensev1/ProfileActivity.java
  app/src/main/java/com/example/soundsensev1/SettingsActivity.java
  app/src/main/res/drawable/ic_baseline_menu_24.xml
  app/src/main/res/layout/activity_data.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/activity_profile.xml
  app/src/main/res/layout/activity_settings.xml
  app/src/main/res/layout/toolbar.xml
  app/src/main/res/menu/main_menu.xml
  app/src/main/res/menu/profile_menu.xml
  app/src/main/res/values/themes.xml
Labels: enhancement

#9 #7-implemented-firebase
  .idea/misc.xml
  app/build.gradle
  app/google-services.json
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/soundsensev1/MainActivity.java
  app/src/main/res/layout/activity_main.xml
  build.gradle
  gradle/wrapper/gradle-wrapper.properties
Labels: enhancement

#11 #7-implemented-firebase
  app/build.gradle
  app/google-services.json
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/soundsensev1/LoginActivity.java
  app/src/main/java/com/example/soundsensev1/MainActivity.java
  app/src/main/java/com/example/soundsensev1/PasswordActivity.java
  app/src/main/java/com/example/soundsensev1/ProfileActivity.java
  app/src/main/java/com/example/soundsensev1/RegistrationActivity.java
  app/src/main/java/com/example/soundsensev1/User.java
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/activity_password.xml
  app/src/main/res/layout/activity_profile.xml
  app/src/main/res/layout/activity_registration.xml
  app/src/main/res/menu/profile_menu.xml
  app/src/main/res/values/themes.xml
Labels: enhancement

#12 pulled-sensor-values
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/soundsensev1/DataActivity.java
  app/src/main/java/com/example/soundsensev1/MainActivity.java
  app/src/main/res/layout/activity_data.xml
Labels: enhancement

#14 pulled-displayed-user-sensor-data
  app/src/main/java/com/example/soundsensev1/DataActivity.java
  app/src/main/java/com/example/soundsensev1/RegistrationActivity.java
  app/src/main/java/com/example/soundsensev1/User.java
  app/src/main/res/layout/activity_data.xml
Labels: enhancement

#17 #13-pulled-displayed-user-sensor-data
  app/src/main/java/com/example/soundsensev1/DataActivity.java
Labels: enhancement

#19 #18-fixed-user-login
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/soundsensev1/LoginActivity.java
  app/src/main/java/com/example/soundsensev1/MainActivity.java
  app/src/main/java/com/example/soundsensev1/ProfileActivity.java
  app/src/main/java/com/example/soundsensev1/SplashActivity.java
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/activity_splash.xml
Labels: bug, enhancement

#21 #16-Updating-The-App
  app/src/main/java/com/example/soundsensev1/ProfileActivity.java
  app/src/main/res/layout/activity_data.xml
  app/src/main/res/layout/activity_profile.xml
Labels: bug

#26 #25-implemented-on-off-setting
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/soundsensev1/SettingsActivity.java
  app/src/main/res/layout/activity_settings.xml
Labels: enhancement

#30 #29-changing-layout-for-main-activity
  app/src/main/java/com/example/soundsensev1/MainActivity.java
  app/src/main/res/drawable/circular_button.xml
  app/src/main/res/drawable/circular_button_green.xml
  app/src/main/res/drawable/circular_button_red.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/toolbar.xml
  app/src/main/res/mipmap-xhdpi/backgound1.JPG
  app/src/main/res/values/colors.xml
Labels: enhancement

#32 #27-implemented-notification-functionality
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/soundsensev1/App.java
  app/src/main/java/com/example/soundsensev1/DataActivity.java
  app/src/main/java/com/example/soundsensev1/MyService.java
  app/src/main/java/com/example/soundsensev1/ProfileActivity.java
  app/src/main/java/com/example/soundsensev1/SettingsActivity.java
Labels: enhancement

#34 #31-Connected-Profile-Editing-to-Firebase
  app/src/main/java/com/example/soundsensev1/ProfileActivity.java
Labels: enhancement

#35 #33-fixed-data-activity-bug
  app/src/main/java/com/example/soundsensev1/DataActivity.java
  app/src/main/java/com/example/soundsensev1/LoginActivity.java
  app/src/main/java/com/example/soundsensev1/MainActivity.java
  app/src/main/java/com/example/soundsensev1/ProfileActivity.java
  app/src/main/java/com/example/soundsensev1/SharedPreferencesHelper.java
  app/src/main/java/com/example/soundsensev1/SplashActivity.java
  app/src/main/res/values/themes.xml
Labels: bug

#37 #36-Added-DeleteList-in-DataActivity
  app/src/main/java/com/example/soundsensev1/DataActivity.java
  app/src/main/java/com/example/soundsensev1/LoginActivity.java
  app/src/main/res/layout/activity_data.xml
  app/src/main/res/values/themes.xml
Labels: enhancement

#42 #33-fixed-data-activity-bug-3
  app/src/main/java/com/example/soundsensev1/DataActivity.java
Labels: bug

#43 #41-implementing-main-activity-button
  app/src/main/java/com/example/soundsensev1/MainActivity.java
  app/src/main/res/layout/activity_main.xml
Labels: enhancement

#47 added background to all activities.
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/soundsensev1/IntroductoryActivity.java
  app/src/main/res/layout/activity_data.xml
  app/src/main/res/layout/activity_introductory.xml
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/layout/activity_password.xml
  app/src/main/res/layout/activity_profile.xml
  app/src/main/res/layout/activity_registration.xml
  app/src/main/res/layout/activity_settings.xml
Labels: enhancement

#49 Retouched some textColor
  app/src/main/java/com/example/soundsensev1/DataActivity.java
  app/src/main/res/layout/activity_data.xml
  app/src/main/res/layout/activity_introductory.xml
  app/src/main/res/layout/activity_login.xml
Labels: enhancement

#51 Made the ListView of DataActivity textColor white
  app/src/main/java/com/example/soundsensev1/DataActivity.java
  app/src/main/java/com/example/soundsensev1/RegistrationActivity.java
  app/src/main/res/layout/activity_data.xml
  app/src/main/res/layout/custom_simple_list_item_1.xml
Labels: enhancement

#52 #44-displayed-information-in-mainactivity-button
  app/src/main/java/com/example/soundsensev1/DataActivity.java
  app/src/main/java/com/example/soundsensev1/MainActivity.java
  app/src/main/java/com/example/soundsensev1/MyService.java
Labels: bug, enhancement

#53 #44-display-information-in-main-activity
  app/src/main/java/com/example/soundsensev1/MainActivity.java
Labels: bug

#55 Added Exception handler for Wifi (off) when signing in and registering
  app/src/main/java/com/example/soundsensev1/LoginActivity.java
  app/src/main/java/com/example/soundsensev1/RegistrationActivity.java
Labels: bug

#57 #56-solve-signout-bug
  app/src/main/java/com/example/soundsensev1/MainActivity.java
  app/src/main/res/drawable/circular_button.xml
  app/src/main/res/layout/activity_data.xml
  app/src/main/res/values/colors.xml
Labels: bug

#63 #62-added-data-timestamps
  app/src/main/java/com/example/soundsensev1/DataActivity.java
  app/src/main/java/com/example/soundsensev1/MainActivity.java
Labels: enhancement

#64 #60-Added-Notifications-on-off
  app/src/main/java/com/example/soundsensev1/MainActivity.java
  app/src/main/java/com/example/soundsensev1/MyService.java
  app/src/main/java/com/example/soundsensev1/SettingsActivity.java
  app/src/main/java/com/example/soundsensev1/SharedPreferencesHelper.java
  app/src/main/res/layout/activity_settings.xml
Labels: enhancement
